# Application configuration (application.yml)
spring:
  application:
    name: event-app

  datasource:
    url: jdbc:postgresql://localhost:5432/event_app_db
    username: devandre
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411

server:
  port: 8088

logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %pid - ${spring.application.name} - %X{traceId:-} - %X{spanId:-} - %5p [%t] %-40.40logger{39} : %m%n%wex"
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %pid - ${spring.application.name} - %X{traceId:-} - %X{spanId:-} - %5p [%t] %-40.40logger{39} : %m%n%wex"
  level:
#    root: INFO
#    org.springframework: INFO
    org.springframework.web: INFO
#    org.springframework.security: INFO
    org.springframework.data: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  file:
#    name: logs/event-app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  tracing:
    sampling:
      probability: 1.0